name: gitbook_search
description: A wrapper API for GitBook to search across pages and spaces. Useful for Saas or products with a search bar for docs and knowledge base.
version: 0.0.1
repository: https://github.com/teta-so/gitbook_search

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  clear_response: ^0.0.2
  equatable: ^2.0.5
  http: ^0.13.5
  light_logger: ^0.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

